### ISSUE TITLE
Secode doesn't work with multiple documents in one .yaml files

### ISSUE THREAD

**Issue by ghost** [crtomirmajer/secode#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/secode", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/secode/cli.py", line 20, in run
    content = encode_secrets(args.file_path, args.decode)
  File "/usr/local/lib/python3.7/site-packages/secode/core.py", line 8, in encode_secrets
    original_payload = read_yaml(file_path)
  File "/usr/local/lib/python3.7/site-packages/secode/core.py", line 17, in read_yaml
    return yaml.load(stream.read())
  File "/usr/local/lib/python3.7/site-packages/ruamel/yaml/main.py", line 331, in load
    return constructor.get_single_data()
  File "/usr/local/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 106, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/local/lib/python3.7/site-packages/ruamel/yaml/composer.py", line 87, in get_single_node
    event.start_mark,
ruamel.yaml.composer.ComposerError: expected a single document in the stream
  in "<unicode string>", line 2, column 1:
    apiVersion: v1
    ^ (line: 2)
but found another document
  in "<unicode string>", line 11, column 1:
    ---
    ^ (line: 11)
```

I will prepare PR with fix. Probably changing .load() to .load_all() should be enough: https://github.com/crtomirmajer/secode/blob/236acc57a57720417df9f9154ab69fa28c40b403/secode/core.py#L17

Example file
```
apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
data:
  key: "value"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
type: Opaque
data:
  key: "value"
```

**Comment by gpolek** [comment]
Pull requests with fix created #2
