### ISSUE TITLE
Unacceptable character / special characters are not allowed

### ISSUE THREAD

**Issue by dheid** [crtomirmajer/secode#6]
I have Python 3.10.5 installed. When I run secode, I get the following error:

```
Traceback (most recent call last):
  File "C:\Apps\python\Python310\Scripts\secode-script.py", line 33, in <module>
    sys.exit(load_entry_point('secode==0.1.0', 'console_scripts', 'secode')())
  File "C:\Apps\python\Python310\lib\site-packages\secode\cli.py", line 25, in run
    content = encode_stream(sys.stdin, args.decode)
  File "C:\Apps\python\Python310\lib\site-packages\secode\core.py", line 16, in encode_stream
    return encode_payload(payload, decode)
  File "C:\Apps\python\Python310\lib\site-packages\secode\core.py", line 22, in encode_payload
    for document in payload:
  File "C:\Apps\python\Python310\lib\site-packages\ruamel\yaml\main.py", line 372, in load_all
    constructor, parser = self.get_constructor_parser(stream)
  File "C:\Apps\python\Python310\lib\site-packages\ruamel\yaml\main.py", line 397, in get_constructor_parser
    self.reader.stream = stream
  File "C:\Apps\python\Python310\lib\site-packages\ruamel\yaml\reader.py", line 117, in stream
    self.check_printable(val)
  File "C:\Apps\python\Python310\lib\site-packages\ruamel\yaml\reader.py", line 250, in check_printable
    raise ReaderError(
ruamel.yaml.reader.ReaderError: unacceptable character #x001b: special characters are not allowed
  in "<unicode string>", position 0
```

**Comment by dheid** [comment]
This only happens in MobaXterm (perhaps because of some color settings). I will close the issue. Sorry!
